# Generated by Django 5.2.10 on 2026-02-04 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name': 'Course Category', 'verbose_name_plural': 'Course Categories'},
        ),
    ]
