# Generated by Django 5.2.10 on 2026-02-04 21:26

import apps.courses.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_content_file_image_text_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='order',
            field=apps.courses.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=apps.courses.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
