# Generated by Django 5.2.10 on 2026-02-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_content_order_module_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='overview',
            field=models.TextField(default='prueb'),
            preserve_default=False,
        ),
    ]
