# Generated by Django 5.2.10 on 2026-02-05 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_overview'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
